name: Publish to NuGet

on:
  push:
    branches: [master]

env:
  PROJECT_PATH: 'DotNet.IXC.ORM/DotNet.IXC.ORM.csproj'
  PROJECT_TEST_PATH: 'DotNet.IXC.ORM.Test/DotNet.IXC.ORM.Test.csproj'
  PROJECT_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: |
          dotnet build ${{ env.PROJECT_PATH }} \
          --no-restore \
          --configuration Release

      - name: Test
        run: |
          dotnet test ${{ env.PROJECT_TEST_PATH }} \
            --configuration Release \
            --verbosity normal
        env:
          IxcOrm__AccessToken: "0:1234567891012345678910123456789101234567891012345678910123456789"
          IxcOrm__ServerDomain: "www.dominio.com.br"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: NuGetRelease
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      - name: Pack
        run: |
          dotnet pack ${{ env.PROJECT_PATH }} \
          --no-build \
          --configuration Release \
          --include-symbols \
          --output ${{ env.PROJECT_OUTPUT_DIRECTORY }}

      - name: Deploy
        run: |
          dotnet nuget push "${{ env.PROJECT_OUTPUT_DIRECTORY }}/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://nuget.org
